export { default as StampsFamousAlternate } from './StampsFamousAlternate'
export { default as StampsFamous } from './StampsFamous'
export { default as StampsImageAlternate } from './StampsImageAlternate'
export { default as StampsImage } from './StampsImage'
export { default as StampsMail } from './StampsMail'