import * as React from "react";
import SvgIcon from "@material-ui/core/SvgIcon";

const SvgPicturePolaroidAlbum1 = (props) =>
  React.createElement(
    SvgIcon,
    props,
    <defs>
      <style>
        {
          ".picture-polaroid-album-1_svg__a{fill:none;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round}"
        }
      </style>
    </defs>,
    <rect
      className="picture-polaroid-album-1_svg__a"
      x={1}
      y={1}
      width={22}
      height={22}
      rx={2}
      ry={2}
    />,
    <rect
      className="picture-polaroid-album-1_svg__a"
      x={4}
      y={4}
      width={4}
      height={4}
      rx={0.5}
      ry={0.5}
    />,
    <rect
      className="picture-polaroid-album-1_svg__a"
      x={10}
      y={4}
      width={4}
      height={4}
      rx={0.5}
      ry={0.5}
    />,
    <rect
      className="picture-polaroid-album-1_svg__a"
      x={16}
      y={4}
      width={4}
      height={4}
      rx={0.5}
      ry={0.5}
    />,
    <rect
      className="picture-polaroid-album-1_svg__a"
      x={4}
      y={10}
      width={4}
      height={4}
      rx={0.5}
      ry={0.5}
    />,
    <rect
      className="picture-polaroid-album-1_svg__a"
      x={10}
      y={10}
      width={4}
      height={4}
      rx={0.5}
      ry={0.5}
    />,
    <rect
      className="picture-polaroid-album-1_svg__a"
      x={16}
      y={10}
      width={4}
      height={4}
      rx={0.5}
      ry={0.5}
    />,
    <rect
      className="picture-polaroid-album-1_svg__a"
      x={4}
      y={16}
      width={4}
      height={4}
      rx={0.5}
      ry={0.5}
    />
  );

export default SvgPicturePolaroidAlbum1;
