export { default as Kindle1 } from './Kindle1'
export { default as KindleHold } from './KindleHold'
export { default as Kindle } from './Kindle'
export { default as Tablet1 } from './Tablet1'
export { default as TabletTouch1 } from './TabletTouch1'
export { default as TabletTouch } from './TabletTouch'
export { default as Tablet } from './Tablet'