import * as React from "react";
import SvgIcon from "@material-ui/core/SvgIcon";

const SvgTablet = (props) =>
  React.createElement(
    SvgIcon,
    props,
    <defs>
      <style>
        {
          ".tablet_svg__a{fill:none;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round}"
        }
      </style>
    </defs>,
    <rect
      className="tablet_svg__a"
      x={2.5}
      y={0.5}
      width={19}
      height={23}
      rx={2}
      ry={2}
    />,
    <rect
      className="tablet_svg__a"
      x={4.5}
      y={3.5}
      width={15}
      height={16}
      rx={0.5}
      ry={0.5}
    />,
    <rect
      className="tablet_svg__a"
      x={6.5}
      y={6.5}
      width={2}
      height={2}
      rx={0.5}
      ry={0.5}
    />,
    <rect
      className="tablet_svg__a"
      x={11}
      y={6.5}
      width={2}
      height={2}
      rx={0.5}
      ry={0.5}
    />,
    <rect
      className="tablet_svg__a"
      x={15.5}
      y={6.5}
      width={2}
      height={2}
      rx={0.5}
      ry={0.5}
    />,
    <rect
      className="tablet_svg__a"
      x={6.5}
      y={10.5}
      width={2}
      height={2}
      rx={0.5}
      ry={0.5}
    />,
    <rect
      className="tablet_svg__a"
      x={11}
      y={10.5}
      width={2}
      height={2}
      rx={0.5}
      ry={0.5}
    />,
    <rect
      className="tablet_svg__a"
      x={6.5}
      y={14.5}
      width={2}
      height={2}
      rx={0.5}
      ry={0.5}
    />,
    <rect
      className="tablet_svg__a"
      x={11}
      y={14.5}
      width={2}
      height={2}
      rx={0.5}
      ry={0.5}
    />,
    <rect
      className="tablet_svg__a"
      x={15.5}
      y={10.5}
      width={2}
      height={2}
      rx={0.5}
      ry={0.5}
    />
  );

export default SvgTablet;
